---
metal_bmc_ignore_macs: []
metal_bmc_allowed_cidrs:
  - 0.0.0.0/0

metal_bmc_bmc_superuser:
metal_bmc_bmc_superuser_pwd:

metal_bmc_nsq_log_level: info
metal_bmc_nsq_tls_enabled: true
metal_bmc_nsq_cert_dir: /certs/nsq
metal_bmc_nsqd_ca_cert:
metal_bmc_nsqd_client_cert:
metal_bmc_nsqd_client_cert_key:

metal_bmc_console_port: 3333
metal_bmc_console_cert_owner: root
metal_bmc_console_cert_group: root
metal_bmc_console_cert_dir: /certs/console
metal_bmc_console_ca_cert:
metal_bmc_console_cert:
metal_bmc_console_key:
