---
pixiecore_dns_servers: []
pixiecore_partition_id: "{{ metal_partition_id }}"

pixiecore_grpc_address: "{{ metal_partition_metal_api_grpc_address }}"
pixiecore_grpc_cert_dir: "{{ metal_partition_metal_api_grpc_cert_dir }}"
pixiecore_grpc_ca_cert: "{{ metal_partition_metal_api_grpc_ca_cert }}"
pixiecore_grpc_client_cert: "{{ metal_partition_metal_api_grpc_client_cert }}"
pixiecore_grpc_client_key: "{{ metal_partition_metal_api_grpc_client_key }}"

pixiecore_metal_api_url: "{{ metal_partition_metal_api_protocol }}:{{ metal_partition_metal_api_addr }}:{{ metal_partition_metal_api_port }}{{ metal_partition_metal_api_basepath }}"
pixiecore_metal_api_hmac_view_key: "{{ metal_partition_metal_api_hmac_view_key }}"
