---
metal_partition_timezone:
metal_partition_id:

metal_partition_metal_api_protocol: https
metal_partition_metal_api_addr:
metal_partition_metal_api_port: 443
metal_partition_metal_api_basepath: "/"
metal_partition_metal_api_hmac_edit_key: change-me
metal_partition_metal_api_hmac_view_key: change-me
metal_partition_metal_apiserver_api_url:

metal_partition_metal_api_grpc_address: "{{ metal_partition_metal_api_addr }}:50051"
metal_partition_metal_api_grpc_cert_dir: /certs/grpc
metal_partition_metal_api_grpc_ca_cert:
metal_partition_metal_api_grpc_client_cert:
metal_partition_metal_api_grpc_client_key:

metal_partition_mgmt_gateway:
