---
- name: Create bridge netdev for vxlans
  copy:
    src: 00-bridge.netdev
    dest: /etc/systemd/network/
  notify: restart systemd-networkd

- name: Render bridge network for vxlans
  template:
    src: bridge.network.j2
    dest: /etc/systemd/network/00-bridge.network
  notify: restart systemd-networkd

- name: Render netdev for vxlan svi
  template:
    src: svi.netdev.j2
    dest: "/etc/systemd/network/{{ (i+81) }}-{{ item.svi.iface }}.netdev"
  notify: restart systemd-networkd
  loop: "{{ systemd_networkd_vxlans }}"
  loop_control:
    index_var: i

- name: Render network for vxlan svi
  template:
    src: svi.network.j2
    dest: "/etc/systemd/network/{{ (i+81) }}-{{ item.svi.iface }}.network"
  notify: restart systemd-networkd
  loop: "{{ systemd_networkd_vxlans }}"
  loop_control:
    index_var: i

- name: Render netdev for vxlan vtep
  template:
    src: vtep.netdev.j2
    dest: "/etc/systemd/network/{{ (i+81) }}-{{ item.vtep.iface }}.netdev"
  notify: restart systemd-networkd
  loop: "{{ systemd_networkd_vxlans }}"
  loop_control:
    index_var: i

- name: Render network for vxlan vtep
  template:
    src: vtep.network.j2
    dest: "/etc/systemd/network/{{ (i+81) }}-{{ item.vtep.iface }}.network"
  notify: restart systemd-networkd
  loop: "{{ systemd_networkd_vxlans }}"
  loop_control:
    index_var: i
