---
nsq_expose_ingress_service_ports: yes

nsq_image_pull_policy: "{{ metal_control_plane_image_pull_policy }}"

nsq_set_resource_limits: true
nsq_nsqd_resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "1"
nsq_nsq_lookupd_resources:
  requests:
    memory: "8Mi"
    cpu: "20m"
  limits:
    memory: "100Mi"
    cpu: "1"

nsq_log_level: info
nsq_broadcast_address: "{{ metal_control_plane_ingress_dns }}"
nsq_nsqd_data_size: 100Mi

nsq_tls_enabled: false
nsq_certs_client_key:
nsq_certs_client_cert:
nsq_certs_ca_cert:
