[default]
extend-ignore-re = [
    # This enables # spellchecker:disable-line
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
    # This enables # spellchecker:off/on
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]

[default.extend-words]
nd = "nd"
cacl = "cacl"
CLOS = "CLOS"
Sover = "Sover"
syncd = "syncd"

[files]
extend-exclude = []
