---
ipam_db_name: ipam-db
ipam_db_namespace: "{{ metal_control_plane_namespace }}"

ipam_db_image_pull_policy: "{{ metal_control_plane_image_pull_policy }}"

ipam_db_storage_size: 5Gi
ipam_db_storage_class:
ipam_db_db: ipam
ipam_db_user: postgres
ipam_db_password: change-me
ipam_db_max_connections: 100

ipam_db_backup_restore_sidecar_image_pull_policy: "{{ metal_control_plane_image_pull_policy }}"
ipam_db_backup_restore_sidecar_provider: local
ipam_db_backup_restore_sidecar_backup_cron_schedule: "*/3 * * * *"
ipam_db_backup_restore_sidecar_log_level: debug
ipam_db_backup_restore_sidecar_object_prefix: "{{ ipam_db_name }}-{{ metal_control_plane_stage_name }}"
ipam_db_backup_restore_sidecar_object_max_keep: 480
ipam_db_backup_restore_sidecar_encryption_key:

ipam_db_backup_restore_sidecar_gcp_bucket_name:
ipam_db_backup_restore_sidecar_gcp_backup_location:
ipam_db_backup_restore_sidecar_gcp_project_id:
ipam_db_backup_restore_sidecar_gcp_serviceaccount_json:

ipam_db_resources:
  requests:
    memory: "128Mi"
    cpu: "20m"
  limits:
    memory: "256Mi"
    cpu: "100m"

ipam_db_registry_auth_enabled: "{{ metal_registry_auth_enabled }}"
ipam_db_registry_auth:
  auths:
    https://index.docker.io/v1/:
      username: "{{ metal_registry_auth_user }}"
      password: "{{ metal_registry_auth_password }}"
      auth: "{{ (metal_registry_auth_user + ':' + metal_registry_auth_password) | b64encode }}"
