---
gardener_logging_namespace: monitoring

gardener_logging_ingress_dns: "loki.{{ metal_control_plane_ingress_dns }}"

gardener_logging_garden_name: "{{ gardener_defaults_garden_name }}"
gardener_logging_ingress_loki_basic_auth_user: promtail
gardener_logging_ingress_loki_basic_auth_password:

gardener_logging_shooted_seeds: []
  # - name: my-shooted-seed
