---
logging_namespace: monitoring
logging_ingress_dns: "loki.{{ metal_control_plane_ingress_dns }}"
logging_ingress_loki_tls: yes
logging_ingress_loki_basic_auth_user: promtail
logging_ingress_loki_basic_auth_password:
logging_ingress_loki_basic_auth_password_salt: "{{ logging_ingress_loki_basic_auth_password | hash('sha1') | truncate(22, True, '') }}"
logging_ingress_annotations: {}
logging_loki_size: 30Gi
