---
gardener_projects_garden_name: "{{ gardener_defaults_garden_name }}"

gardener_projects: []
# - name: seed-a
#   description:
#   members:
#     kind:
#     name:
#     role:
#     roles: []
#  protected_toleration:

gardener_project_defaults:
  namespace: garden
  owner: admin
  additional_annotations: {}
  protected_toleration: true
  members: []
