---
zitadel_init_image: ghcr.io/metal-stack/zitadel-init
zitadel_init_image_tag: v0.2.0

# currently this is overwritten because we require to have the latest version for zitadel-init
# don't forget to remove this again until the helm chart was updated to use at least this version
zitadel_image_tag: v4.7.0

zitadel_endpoint: zitadel.{{ metal_control_plane_ingress_dns }}
zitadel_namespace: "{{ metal_control_plane_namespace }}"
zitadel_external_domain:
zitadel_ingress_dns: https://zitadel.{{ metal_control_plane_ingress_dns }}:443
zitadel_port: 443
zitadel_skip_verify_tls: false
zitadel_insecure: false

zitadel_initial_instance: metal-stack
zitadel_initial_org: metal-stack

zitadel_admin_password: Password1!
zitadel_master_key: x123456789012345678901234567891y
zitadel_db_address: zitadel-db
zitadel_db_password: change-me

zitadel_enabled_ingress: true

zitadel_init_config: {}
  # static_users:
  #   - first_name: Olli
  #     last_name: Owner
  #     email: olli.owner@metal-stack.io
  #     password: Olli.Owner123!
  # project:
  #   id: metal-stack
  #   name: metal-stack
  # application:
  #   id: metal-stack
  #   name: metal-stack
  #   redirect_uri: http://v2.api.172.17.0.1.nip.io:8080/auth/openid-connect/callback

zitadel_image_pull_policy: "{{ metal_control_plane_image_pull_policy }}"
