---
galaxy_info:
  role_name: metal-python
  author: metal-stack
  description: Installs the metal-python client library.
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags: []
  platforms:
    - name: GenericLinux
      versions:
        - all

dependencies:
  - role: metal-roles/common/roles/defaults
