---
rethinkdb_name: rethinkdb
rethinkdb_namespace: "{{ metal_control_plane_namespace }}"

rethinkdb_image_pull_policy: "{{ metal_control_plane_image_pull_policy }}"

rethinkdb_storage_size: 5Gi
rethinkdb_storage_class:
rethinkdb_password: change-me

rethinkdb_backup_restore_sidecar_image_pull_policy: "{{ metal_control_plane_image_pull_policy }}"
rethinkdb_backup_restore_sidecar_provider: local
rethinkdb_backup_restore_sidecar_backup_cron_schedule: "*/3 * * * *"
rethinkdb_backup_restore_sidecar_log_level: debug

rethinkdb_backup_restore_sidecar_gcp_bucket_name:
rethinkdb_backup_restore_sidecar_gcp_backup_location:
rethinkdb_backup_restore_sidecar_gcp_project_id:
rethinkdb_backup_restore_sidecar_gcp_serviceaccount_json:

rethinkdb_backup_restore_sidecar_object_max_keep:

rethinkdb_expose_frontend: no
rethinkdb_ingress_dns: rethinkdb.{{ metal_control_plane_ingress_dns }}

rethinkdb_resources:
  requests:
    memory: "2Gi"
    cpu: "200m"
  limits:
    memory: "4Gi"
    cpu: "500m"

rethinkdb_registry_auth_enabled: "{{ metal_registry_auth_enabled }}"
rethinkdb_registry_auth:
  auths:
    docker.io:
      username: "{{ metal_registry_auth_user }}"
      password: "{{ metal_registry_auth_password }}"
      auth: "{{ (metal_registry_auth_user + ':' + metal_registry_auth_password) | b64encode }}"
