---
masterdata_db_name: masterdata-db
masterdata_db_namespace: "{{ metal_control_plane_namespace }}"

masterdata_db_image_pull_policy: "{{ metal_control_plane_image_pull_policy }}"

masterdata_db_storage_size: 5Gi
masterdata_db_storage_class:
masterdata_db_db: masterdata
masterdata_db_user: postgres
masterdata_db_password: change-me
masterdata_db_max_connections: 100

masterdata_db_backup_restore_sidecar_image_pull_policy: "{{ metal_control_plane_image_pull_policy }}"
masterdata_db_backup_restore_sidecar_provider: local
masterdata_db_backup_restore_sidecar_backup_cron_schedule: "*/3 * * * *"
masterdata_db_backup_restore_sidecar_log_level: debug
masterdata_db_backup_restore_sidecar_object_prefix: "{{ masterdata_db_name }}-{{ metal_control_plane_stage_name }}"
masterdata_db_backup_restore_sidecar_object_max_keep:
masterdata_db_backup_restore_sidecar_encryption_key:

masterdata_db_backup_restore_sidecar_gcp_bucket_name:
masterdata_db_backup_restore_sidecar_gcp_backup_location:
masterdata_db_backup_restore_sidecar_gcp_project_id:
masterdata_db_backup_restore_sidecar_gcp_serviceaccount_json:

masterdata_db_resources:
  requests:
    memory: "128Mi"
    cpu: "20m"
  limits:
    memory: "256Mi"
    cpu: "100m"

masterdata_db_registry_auth_enabled: "{{ metal_registry_auth_enabled }}"
masterdata_db_registry_auth:
  auths:
    https://index.docker.io/v1/:
      username: "{{ metal_registry_auth_user }}"
      password: "{{ metal_registry_auth_password }}"
      auth: "{{ (metal_registry_auth_user + ':' + metal_registry_auth_password) | b64encode }}"
