---
valkey_chart_ref: valkey
# for testing the chart locally in the mini-lab
# valkey_chart_ref: /helm-charts/charts/valkey

valkey_namespace: "{{ metal_control_plane_namespace }}"

valkey_replicas: 3
valkey_password: change-me-soon

valkey_size: 10Gi
valkey_storage_class: ""

valkey_image_pull_policy: "{{ metal_control_plane_image_pull_policy }}"

valkey_registry_auth_enabled: "{{ metal_registry_auth_enabled }}"
valkey_registry_auth:
  auths:
    "{{ metal_registry_url }}":
      username: "{{ metal_registry_auth_user }}"
      password: "{{ metal_registry_auth_password }}"
      auth: "{{ (metal_registry_auth_user + ':' + metal_registry_auth_password) | b64encode }}"
