---
galaxy_info:
  role_name: gardener-monitoring-certs
  author: metal-stack
  description: Deploys certificates used for monitoring components of the Gardener.
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags: []
  platforms:
    - name: GenericLinux
      versions:
        - all

dependencies:
  - role: metal-roles/common/roles/defaults
  - role: metal-roles/control-plane/roles/defaults
  - role: metal-roles/control-plane/roles/gardener-defaults
