---
- name: check mandatory variables for this role are set
  assert:
    fail_msg: "not all mandatory variables given, check role documentation"
    quiet: yes
    that:
      - gitlab_runner_url is not none
      - gitlab_runner_token is not none
      - gitlab_runner_description is not none
      - gitlab_runner_tags is not none
      - gitlab_runner_hostpath is not none

- name: install docker as a prerequisite to gitlabci
  apt:
    name:
    - docker.io

- name: Copy ssh key pair for gitlab runner
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode}}"
  loop:
  - content: "{{ gitlab_runner_ssh_privkey }}"
    dest: "{{ gitlab_runner_hostpath }}/ssh/id_rsa"
    mode: "0600"
  - content: "{{ gitlab_runner_ssh_pubkey }}"
    dest: "{{ gitlab_runner_hostpath }}/ssh/id_rsa.pub"
    mode: "0644"
  when: gitlab_runner_ssh_privkey and gitlab_runner_ssh_pubkey

- name: check if runner is already registered to avoid double registration
  command: grep -Fxq "[[runners]]" {{ gitlab_runner_hostpath }}/etc/gitlab-runner/config.toml
  register: check_runners
  failed_when: false
  check_mode: false
  changed_when: false

- name: register runner to GitLab when no config exists
  command: /usr/bin/docker run --rm \
    -v "/run/docker/.sock:/run/docker.sock" \
    -v "{{ gitlab_runner_hostpath }}/etc/gitlab-runner:/etc/gitlab-runner" \
    -v "{{ gitlab_runner_hostpath }}/cache:/cache" \
    -v "{{ gitlab_runner_hostpath }}/ssh:/ssh" \
    '{{ gitlab_runner_image }}:{{ gitlab_runner_image_tag }}' register >
    --non-interactive
    --url '{{ gitlab_runner_url }}'
    --registration-token '{{ gitlab_runner_token }}'
    --description '{{ gitlab_runner_description }}'
    --executor docker
    --docker-image '{{ gitlab_runner_image_tag }}'
    --tag-list '{{ gitlab_runner_tags }}'
  when: check_runners.rc != 0

- name: deploy gitlab-ci service
  include_role:
    name: ansible-common/roles/systemd-docker-service
  vars:
    systemd_service_name: gitlab-ci
    systemd_docker_image_name: "{{ gitlab_runner_image }}"
    systemd_docker_image_tag: "{{ gitlab_runner_image_tag }}"
    systemd_service_after: docker.service
    systemd_docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ gitlab_runner_hostpath }}/etc/gitlab-runner:/etc/gitlab-runner"
      - "{{ gitlab_runner_hostpath }}/cache:/cache"
      - "{{ gitlab_runner_hostpath }}/ssh:/ssh"
    systemd_docker_command:
      - run

- name: set gitlab-runner volume config
  lineinfile:
    path: "{{ gitlab_runner_hostpath }}/etc/gitlab-runner/config.toml"
    regexp: "volumes"
    line: '    volumes = ["/gitlabci/cache:/cache","/gitlabci/ssh:/ssh"]'
    state: present
