---
metal_registry_url: "https://index.docker.io/v1/"
metal_registry_auth_enabled: no
metal_registry_auth_user: ""
metal_registry_auth_password: ""

metal_stack_release:
  mapping:
    # binaries
    metal_hammer_image_tag: "binaries.metal-stack.metal-hammer.version"
    metal_hammer_image_url: "binaries.metal-stack.metal-hammer.url"
    metal_kernel_tag: "binaries.metal-stack.kernel.version"
    metal_kernel_url: "binaries.metal-stack.kernel.url"
    metalctl_version: "binaries.metal-stack.metalctl.version"
    # control plane
    metal_api_image_tag: "docker-images.metal-stack.control-plane.metal-api.tag"
    metal_api_image_name: "docker-images.metal-stack.control-plane.metal-api.name"
    metal_apiserver_image_tag: "docker-images.metal-stack.control-plane.metal-apiserver.tag"
    metal_apiserver_image_name: "docker-images.metal-stack.control-plane.metal-apiserver.name"
    metal_metalctl_image_tag: "docker-images.metal-stack.control-plane.metalctl.tag"
    metal_metalctl_image_name: "docker-images.metal-stack.control-plane.metalctl.name"
    metal_masterdata_api_image_tag: "docker-images.metal-stack.control-plane.masterdata-api.tag"
    metal_masterdata_api_image_name: "docker-images.metal-stack.control-plane.masterdata-api.name"
    metal_console_image_tag: "docker-images.metal-stack.control-plane.metal-console.tag"
    metal_console_image_name: "docker-images.metal-stack.control-plane.metal-console.name"
    metal_ipam_image_tag: "docker-images.metal-stack.control-plane.ipam.tag"
    metal_ipam_image_name: "docker-images.metal-stack.control-plane.ipam.name"
    metal_metrics_exporter_image_tag: "docker-images.metal-stack.control-plane.metal-metrics-exporter.tag"
    metal_metrics_exporter_image_name: "docker-images.metal-stack.control-plane.metal-metrics-exporter.name"
    rethinkdb_exporter_name: "docker-images.metal-stack.control-plane.rethinkdb-exporter.name"
    rethinkdb_exporter_tag: "docker-images.metal-stack.control-plane.rethinkdb-exporter.tag"
    # partition
    metal_core_image_tag: "docker-images.metal-stack.partition.metal-core.tag"
    metal_core_image_name: "docker-images.metal-stack.partition.metal-core.name"
    pixiecore_image_tag: "docker-images.metal-stack.partition.pixiecore.tag"
    pixiecore_image_name: "docker-images.metal-stack.partition.pixiecore.name"
    metal_bmc_image_tag: "docker-images.metal-stack.partition.metal-bmc.tag"
    metal_bmc_image_name: "docker-images.metal-stack.partition.metal-bmc.name"
    image_cache_sync_image_tag: "docker-images.metal-stack.partition.metal-image-cache-sync.tag"
    image_cache_sync_image_name: "docker-images.metal-stack.partition.metal-image-cache-sync.name"
    sonic_configdb_utils_image_tag: "docker-images.metal-stack.partition.sonic-configdb-utils.tag"
    sonic_configdb_utils_image_name: "docker-images.metal-stack.partition.sonic-configdb-utils.name"
    # generic
    metal_db_backup_restore_sidecar_image_tag: "docker-images.metal-stack.generic.backup-restore-sidecar.tag"
    metal_db_backup_restore_sidecar_image_name: "docker-images.metal-stack.generic.backup-restore-sidecar.name"
    ipam_db_backup_restore_sidecar_image_tag: "docker-images.metal-stack.generic.backup-restore-sidecar.tag"
    ipam_db_backup_restore_sidecar_image_name: "docker-images.metal-stack.generic.backup-restore-sidecar.name"
    masterdata_db_backup_restore_sidecar_image_tag: "docker-images.metal-stack.generic.backup-restore-sidecar.tag"
    masterdata_db_backup_restore_sidecar_image_name: "docker-images.metal-stack.generic.backup-restore-sidecar.name"
    headscale_db_backup_restore_sidecar_image_tag: "docker-images.metal-stack.generic.backup-restore-sidecar.tag"
    headscale_db_backup_restore_sidecar_image_name: "docker-images.metal-stack.generic.backup-restore-sidecar.name"
    auditing_timescaledb_backup_restore_sidecar_image_tag: "docker-images.metal-stack.generic.backup-restore-sidecar.tag"
    auditing_timescaledb_backup_restore_sidecar_image_name: "docker-images.metal-stack.generic.backup-restore-sidecar.name"
    # gardener
    firewall_controller_manager_image_tag: "docker-images.metal-stack.gardener.firewall-controller-manager.tag"
    firewall_controller_manager_image_name: "docker-images.metal-stack.gardener.firewall-controller-manager.name"
    gardener_extension_provider_metal_image_tag: "docker-images.metal-stack.gardener.gardener-extension-provider-metal.tag"
    gardener_extension_provider_metal_image_name: "docker-images.metal-stack.gardener.gardener-extension-provider-metal.name"
    gardener_extension_provider_metal_repo_url: "docker-images.metal-stack.gardener.gardener-extension-provider-metal.repository"
    gardener_os_controller_image_tag: "docker-images.metal-stack.gardener.os-metal-extension.tag"
    gardener_os_controller_image_name: "docker-images.metal-stack.gardener.os-metal-extension.name"
    gardener_mcm_provider_metal_image_name: "docker-images.metal-stack.gardener.machine-controller-manager-provider-metal.name"
    gardener_mcm_provider_metal_image_tag: "docker-images.metal-stack.gardener.machine-controller-manager-provider-metal.tag"
    gardener_extension_audit_image_name: "docker-images.metal-stack.gardener.gardener-extension-audit.name"
    gardener_extension_audit_image_tag: "docker-images.metal-stack.gardener.gardener-extension-audit.tag"
    gardener_extension_backup_s3_image_tag: "docker-images.metal-stack.gardener.gardener-extension-backup-s3.tag"
    gardener_extension_backup_s3_image_name: "docker-images.metal-stack.gardener.gardener-extension-backup-s3.name"
    gardener_extension_dns_powerdns_image_tag: "docker-images.metal-stack.gardener.gardener-extension-dns-powerdns.tag"
    gardener_extension_dns_powerdns_image_name: "docker-images.metal-stack.gardener.gardener-extension-dns-powerdns.name"
    gardener_extension_csi_driver_lvm_image_tag: "docker-images.metal-stack.gardener.gardener-extension-csi-driver-lvm.tag"
    gardener_extension_csi_driver_lvm_image_name: "docker-images.metal-stack.gardener.gardener-extension-csi-driver-lvm.name"
    gardener_extension_ontap_image_tag: "docker-images.metal-stack.gardener.gardener-extension-ontap.tag"
    gardener_extension_ontap_image_name: "docker-images.metal-stack.gardener.gardener-extension-ontap.name"
    # kubernetes
    csi_lvm_controller_image_tag: "docker-images.metal-stack.kubernetes.csi-lvm-controller.tag"
    csi_lvm_controller_image_name: "docker-images.metal-stack.kubernetes.csi-lvm-controller.name"
    csi_lvm_provisioner_image_tag: "docker-images.metal-stack.kubernetes.csi-lvm-provisioner.tag"
    csi_lvm_provisioner_image_name: "docker-images.metal-stack.kubernetes.csi-lvm-provisioner.name"
    duros_controller_image_tag: "docker-images.metal-stack.kubernetes.duros-controller.tag"
    duros_controller_image_name: "docker-images.metal-stack.kubernetes.duros-controller.name"
    metal_cloud_controller_manager_image_tag: "docker-images.metal-stack.kubernetes.metal-ccm.tag"
    metal_cloud_controller_manager_image_name: "docker-images.metal-stack.kubernetes.metal-ccm.name"
    audit_forwarder_image_tag: "docker-images.metal-stack.kubernetes.audit-forwarder.tag"
    audit_forwarder_image_name: "docker-images.metal-stack.kubernetes.audit-forwarder.name"
    node_init_image_tag: "docker-images.metal-stack.kubernetes.node-init.tag"
    node_init_image_name: "docker-images.metal-stack.kubernetes.node-init.name"
    droptailer_image_tag: "docker-images.metal-stack.kubernetes.droptailer.tag"
    droptailer_image_name: "docker-images.metal-stack.kubernetes.droptailer.name"
    capms_controller_name: "docker-images.metal-stack.kubernetes.cluster-api-provider-metal-stack-controller.name"
    capms_controller_tag: "docker-images.metal-stack.kubernetes.cluster-api-provider-metal-stack-controller.tag"
    # third party
    event_exporter_name: "docker-images.third-party.control-plane.event-exporter.name"
    event_exporter_tag: "docker-images.third-party.control-plane.event-exporter.tag"
    nsq_image_tag: "docker-images.third-party.control-plane.nsq.tag"
    nsq_image_name: "docker-images.third-party.control-plane.nsq.name"
    ipam_db_image_tag: "docker-images.third-party.control-plane.ipam-db.tag"
    ipam_db_image_name: "docker-images.third-party.control-plane.ipam-db.name"
    masterdata_db_image_tag: "docker-images.third-party.control-plane.masterdata-db.tag"
    masterdata_db_image_name: "docker-images.third-party.control-plane.masterdata-db.name"
    metal_db_image_tag: "docker-images.third-party.control-plane.metal-db.tag"
    metal_db_image_name: "docker-images.third-party.control-plane.metal-db.name"
    headscale_image_tag: "docker-images.third-party.control-plane.headscale.tag"
    headscale_image_name: "docker-images.third-party.control-plane.headscale.name"
    headscale_db_image_tag: "docker-images.third-party.control-plane.headscale-db.tag"
    headscale_db_image_name: "docker-images.third-party.control-plane.headscale-db.name"
    auditing_timescaledb_image_name: "docker-images.third-party.control-plane.timescaledb.name"
    auditing_timescaledb_image_tag: "docker-images.third-party.control-plane.timescaledb.tag"
    image_cache_coredns_image_tag: "docker-images.third-party.partition.image-cache-coredns.tag"
    image_cache_coredns_image_name: "docker-images.third-party.partition.image-cache-coredns.name"
    image_cache_haproxy_image_tag: "docker-images.third-party.partition.image-cache-haproxy.tag"
    image_cache_haproxy_image_name: "docker-images.third-party.partition.image-cache-haproxy.name"
    prometheus_image_tag: "docker-images.third-party.partition.prometheus.tag"
    prometheus_image_name: "docker-images.third-party.partition.prometheus.name"
    promtail_image_tag: "docker-images.third-party.partition.promtail.tag"
    promtail_image_name: "docker-images.third-party.partition.promtail.name"
    ztp_nginx_image_tag: "docker-images.third-party.partition.ztp-nginx.tag"
    ztp_nginx_image_name: "docker-images.third-party.partition.ztp-nginx.name"
    # third-party gardener
    gardener_admission_controller_image_tag: "docker-images.third-party.gardener.admission-controller.tag"
    gardener_admission_controller_image_name: "docker-images.third-party.gardener.admission-controller.name"
    gardener_apiserver_image_tag: "docker-images.third-party.gardener.api-server.tag"
    gardener_apiserver_image_name: "docker-images.third-party.gardener.api-server.name"
    gardener_operator_image_tag: "docker-images.third-party.gardener.operator.tag"
    gardener_operator_image_name: "docker-images.third-party.gardener.operator.name"
    gardener_controller_manager_image_tag: "docker-images.third-party.gardener.controller-manager.tag"
    gardener_controller_manager_image_name: "docker-images.third-party.gardener.controller-manager.name"
    gardener_scheduler_image_tag: "docker-images.third-party.gardener.scheduler.tag"
    gardener_scheduler_image_name: "docker-images.third-party.gardener.scheduler.name"
    gardener_gardenlet_image_tag: "docker-images.third-party.gardener.gardenlet.tag"
    gardener_gardenlet_image_name: "docker-images.third-party.gardener.gardenlet.name"
    gardener_virtual_garden_api_server_version: "docker-images.third-party.gardener.virtual-garden-apiserver.tag"
    gardener_extension_provider_gcp_image_tag: "docker-images.third-party.gardener.extension-provider-gcp.tag"
    gardener_extension_provider_gcp_image_name: "docker-images.third-party.gardener.extension-provider-gcp.name"
    gardener_extension_admission_gcp_image_tag: "docker-images.third-party.gardener.extension-admission-gcp.tag"
    gardener_extension_admission_gcp_image_name: "docker-images.third-party.gardener.extension-admission-gcp.name"
    gardener_extension_networking_calico_image_tag: "docker-images.third-party.gardener.networking-calico.tag"
    gardener_extension_networking_calico_image_name: "docker-images.third-party.gardener.networking-calico.name"
    gardener_extension_networking_cilium_image_tag: "docker-images.third-party.gardener.networking-cilium.tag"
    gardener_extension_networking_cilium_image_name: "docker-images.third-party.gardener.networking-cilium.name"
    gardener_extension_shoot_cert_service_image_tag: "docker-images.third-party.gardener.shoot-cert-service.tag"
    gardener_extension_shoot_cert_service_image_name: "docker-images.third-party.gardener.shoot-cert-service.name"
    gardener_extension_shoot_dns_service_image_tag: "docker-images.third-party.gardener.shoot-dns-service.tag"
    gardener_extension_shoot_dns_service_image_name: "docker-images.third-party.gardener.shoot-dns-service.name"
    gardener_metrics_exporter_image_tag: "docker-images.third-party.gardener.metrics-exporter.tag"
    gardener_metrics_exporter_image_name: "docker-images.third-party.gardener.metrics-exporter.name"
    gardener_extension_acl_image_name: "docker-images.third-party.gardener.acl-extension.name"
    gardener_extension_acl_image_tag: "docker-images.third-party.gardener.acl-extension.tag"
    # helm-charts
    metal_helm_chart_version: "helm-charts.metal-stack.metal-control-plane.version"
    metal_helm_chart_repo: "helm-charts.metal-stack.metal-control-plane.repository"
    logging_chart_version: "helm-charts.logging.loki.version"
    logging_chart_repo: "helm-charts.logging.loki.repository"
    logging_promtail_chart_version: "helm-charts.logging.promtail.version"
    logging_promtail_chart_repo: "helm-charts.logging.promtail.repository"
    prometheus_chart_version: "helm-charts.monitoring.kube-prometheus-stack.version"
    prometheus_stack_repo: "helm-charts.monitoring.kube-prometheus-stack.repository"
    thanos_chart_version: "helm-charts.monitoring.thanos.version"
    thanos_chart_repo: "helm-charts.monitoring.thanos.repository"
    valkey_chart_repo: "helm-charts.metal-stack.valkey.repository"
    valkey_chart_version: "helm-charts.metal-stack.valkey.version"
    # gardener-extension oci helm-charts
    gardener_extension_acl_helm_chart: "docker-images.third-party.gardener.acl-extension.charts.extension"
    gardener_extension_admission_acl_helm_chart_runtime: "docker-images.third-party.gardener.acl-extension.charts.runtime"
    gardener_extension_admission_acl_helm_chart_application: "docker-images.third-party.gardener.acl-extension.charts.application"
    gardener_extension_audit_helm_chart: "docker-images.metal-stack.gardener.gardener-extension-audit.charts.extension"
    gardener_extension_backup_s3_helm_chart: "docker-images.metal-stack.gardener.gardener-extension-backup-s3.charts.extension"
    gardener_extension_csi_driver_lvm_helm_chart: "docker-images.metal-stack.gardener.gardener-extension-csi-driver-lvm.charts.extension"
    gardener_extension_ontap_helm_chart: "docker-images.metal-stack.gardener.gardener-extension-ontap.charts.extension"
    gardener_extension_dns_powerdns_helm_chart: "docker-images.metal-stack.gardener.gardener-extension-dns-powerdns.charts.extension"
    gardener_extension_networking_calico_helm_chart: "docker-images.third-party.gardener.networking-calico.charts.extension"
    gardener_extension_admission_calico_helm_chart_runtime: "docker-images.third-party.gardener.networking-calico.charts.runtime"
    gardener_extension_admission_calico_helm_chart_application: "docker-images.third-party.gardener.networking-calico.charts.application"
    gardener_extension_networking_cilium_helm_chart: "docker-images.third-party.gardener.networking-cilium.charts.extension"
    gardener_extension_admission_cilium_helm_chart_runtime: "docker-images.third-party.gardener.networking-cilium.charts.runtime"
    gardener_extension_admission_cilium_helm_chart_application: "docker-images.third-party.gardener.networking-cilium.charts.application"
    gardener_extension_os_metal_helm_chart: "docker-images.metal-stack.gardener.os-metal-extension.charts.extension"
    gardener_extension_provider_gcp_helm_chart: "docker-images.third-party.gardener.extension-provider-gcp.charts.extension"
    gardener_extension_admission_gcp_helm_chart_runtime: "docker-images.third-party.gardener.extension-admission-gcp.charts.runtime"
    gardener_extension_admission_gcp_helm_chart_application: "docker-images.third-party.gardener.extension-admission-gcp.charts.application"
    gardener_extension_provider_metal_helm_chart: "docker-images.metal-stack.gardener.gardener-extension-provider-metal.charts.extension"
    gardener_extension_admission_metal_helm_chart_runtime: "docker-images.metal-stack.gardener.gardener-extension-provider-metal.charts.runtime"
    gardener_extension_admission_metal_helm_chart_application: "docker-images.metal-stack.gardener.gardener-extension-provider-metal.charts.application"
    gardener_extension_shoot_cert_service_helm_chart: "docker-images.third-party.gardener.shoot-cert-service.charts.extension"
    gardener_extension_shoot_dns_service_helm_chart: "docker-images.third-party.gardener.shoot-dns-service.charts.extension"
    gardener_extension_admission_shoot_dns_service_helm_chart_application: "docker-images.third-party.gardener.shoot-dns-service.charts.application"
    gardener_extension_admission_shoot_dns_service_helm_chart_runtime: "docker-images.third-party.gardener.shoot-dns-service.charts.runtime"
    gardener_gardenlet_helm_chart: "docker-images.third-party.gardener.gardenlet.charts.ref"
    gardener_operator_helm_chart: "docker-images.third-party.gardener.operator.charts.ref"
    # monitoring
    webhook_logger_image_name: "docker-images.third-party.control-plane.webhook-logger.name"
    webhook_logger_image_tag: "docker-images.third-party.control-plane.webhook-logger.tag"
    # repositories
    gardener_repo_url: "repositories.third-party.gardener.gardener.url"
    gardener_repo_ref: "repositories.third-party.gardener.gardener.ref"
    thanos_image_name: "docker-images.third-party.control-plane.thanos.name"
    thanos_image_tag: "docker-images.third-party.control-plane.thanos.tag"
