---
metal_core_log_driver: journald
metal_core_log_level: warn
metal_core_rack_id:

metal_core_reconfigure_switch: true
metal_core_reconfigure_switch_interval: 10s

metal_core_grpc_address: "{{ metal_partition_metal_api_grpc_address }}"
metal_core_grpc_cert_dir: "{{ metal_partition_metal_api_grpc_cert_dir }}"
metal_core_grpc_ca_cert: "{{ metal_partition_metal_api_grpc_ca_cert }}"
metal_core_grpc_client_cert: "{{ metal_partition_metal_api_grpc_client_cert }}"
metal_core_grpc_client_key: "{{ metal_partition_metal_api_grpc_client_key }}"
metal_core_metal_apiserver_api_url: "{{ metal_partition_metal_apiserver_api_url }}"
metal_core_metal_apiserver_token:

metal_core_additional_bridge_vids: []
metal_core_additional_bridge_ports: []
metal_core_additional_volume_mounts: []

metal_core_consider_hosts_file_resolution: false

metal_core_interfaces_tpl_file: ""
metal_core_frr_tpl_file: ""

metal_core_pxe_vlan_id: 4000
