name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: metalstack/metal-deployment-base:latest
    steps:
      - uses: actions/checkout@v6
      - name: Test
        run: |
          make test

  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check spelling
        uses: crate-ci/typos@master

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: markdownlint-cli
        uses: DavidAnson/markdownlint-cli2-action@main
        # for now we need to ignore, it throws a lot of errors that need to be fixed over time
        continue-on-error: true

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run yamllint
        uses: karancode/yamllint-github-action@master
        # for now we need to ignore, it throws a lot of errors that need to be fixed over time
        continue-on-error: true

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        # for now we need to ignore, it throws a lot of errors that need to be fixed over time
        continue-on-error: true
